### ISSUE TITLE
Specific issues and improvements for the explanation of models

### ISSUE THREAD

**Issue by pedrohbraga** [QCBSRworkshops/workshop04#11]
In general, there is a need to better explain the general linear models in this presentation. While the objective of the workshops is to help people with prior knowledge of statistics to use `R` for their research, this workshop has an unbalanced presentation of its content. For instance, it goes back to the basics by recalling concepts of mean, variance and deviation, but it goes pretty fast on linear models, simple regression and other topics.

It would be a good idea for this workshop to contain an introductory step that describes the concept of a model (in general; not only linear ones), recalling what are predictors (explanatory) and response (target) variables, showing what is the idea of $Y = f(X) + \epsilon$, and only then, begin with general linear models.

Whenever explaining general linear models, a type of standard has to be followed, where the equation is shown followed by its assumptions described in prose and, whenever possible, with the corresponding mathematical notation, as in:

```
We now define what we will call the simple linear regression model,
$$Y_i = \beta_0 + \beta_1 x_i + \epsilon_i$$
where, 
$$\epsilon_i \sim N(0, \sigma^2)$$

Meaning that:
1. The relationship between $Y$ and $x$ is linear, of the form $\beta_0 + \beta_1 x_i$;
2. The errors $ϵ$ are independent.
3. The errors, $ϵ$ are normally distributed. That is the “error” around the line follows a normal distribution.
4. At each value of $x$, the variance of $Y$ is the same, $σ^2$.
```

Following this, complexity can then be built by including more explanatory variables (for multiple linear regressions) and changing the variable types.

Recommended changes:
- [ ] ~~Change slide 15 title to "General Linear Models";~~
- [x] The explanation within the "What are linear models" needs to be improved and the information must be put, either in the form of a table or described along with the equation.
- [x] If the general changes are accepted, the slide "Defining linear models" (currently, number 15) can be omitted or replaced by a simpler version, as this is further explained across the other slides.

**Comment by dschoenig** [comment]
Commit 2062207bf44770a9fb87cfa9e0efef9fab73467a addresses these issues for the English and French version in an overhaul of the section on linear regression:

- The example data set is introduced as early as possible in attempt to make the first part less abstract.
- Active learning: Additional queues for discussion in small groups and an additional challenge was added. 
- Linear models are introduced in the context of scientific investigation, i.e. as a tool to investigate a research question or hypothesis.
- More emphasis is put on how to use use R to interpret models in the light of the research question / hypothesis.
- More presenter notes are added with important aspects and/or common points of confusion.
- A consistent mathematical notation was chosen; differences between mathematical notation and model formulation in R are presented on a dedicated slide, with the aim that mathematical notation and R notation are not confused.
- A consistent way to present and discuss diagnostic plots was chosen.
- The section now uses only the terms response and predictor, which are the standard in the (applied) statistical literature. 
- An additional slide on the various terms for predictor and response was added (could probably be improved).
- Basics on measures of central tendency and location have been shortened into a single slide.

The section on multiple linear regression deserves an issue of its own. I only changed the mathematical presentation (now consistent with the simple linear regression), and I added a note at the end, that the parameters of the model should not even be interpreted since it clearly violates the assumptions.

I decided not to use the term "General linear model" as it is generally used in the context of multivariate methods, while the literature refers to the models used in this workshop simply as "linear model".
